trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DockerCompose@0
  displayName: Build CI Containers
  inputs:
    action: Run A Docker Compose command
    dockerComposeFile: docker-compose.ci.yml
    abortOnContainerExit: true
    buildImages: true
    dockerComposeCommand: -f docker-compose.ci.yml build

- task: DockerCompose@0
  displayName: Run CI Containers
  inputs:
    action: Run A Docker Compose command
    dockerComposeFile: docker-compose.ci.yml
    abortOnContainerExit: true
    buildImages: true
    dockerComposeCommand: -f docker-compose.ci.yml up --abort-on-container-exit --exit-code-from web

- task: Docker@2
  inputs:
    containerRegistry: 'KananRahimovContainers'
    repository: 'surveybox-be'
    command: 'buildAndPush'
    Dockerfile: './Dockerfile'
    tags: |
      latest
      $(Build.BuildId)
  displayName: 'Build and Push Docker Image'
