version: '2'

services:
  postgres:
    image: postgres:9.6
  web:
    environment:
      - DJANGO_SECRET_KEY=ci
      - DJANGO_CONFIGURATION=CI
    image: web
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py test --verbose -d"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
