site_name: surveybox
site_description: Backend for SurveyBox.
repo_url: https://github.com/KenanBek/surveybox-be
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/KenanBek">KenanBek</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
